--
-- PostgreSQL database dump
--

\restrict f8mx5zOTvs2XqpSZuAuCv5zbmPQjRw2PtNdjmlqIKB9b3uZm6brGdOYDVxEhlyH

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2026-03-23 14:18:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.auth_codes (
    email character varying(255) NOT NULL,
    code character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.auth_codes OWNER TO postgres;

CREATE TABLE public.coursework (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    due_date timestamp NOT NULL,
    title character varying(255) NOT NULL,
    weighting integer,
    module_id bigint NOT NULL,
    completed boolean DEFAULT false NOT NULL,
    completed_at timestamp without time zone,
    score_percent numeric(38,2),
    marks_achieved numeric(6,2),
    marks_total numeric(6,2),
    CONSTRAINT coursework_marks_achieved_chk CHECK (((marks_achieved IS NULL) OR (marks_achieved >= (0)::numeric))),
    CONSTRAINT coursework_marks_pair_chk CHECK ((((marks_achieved IS NULL) AND (marks_total IS NULL)) OR ((marks_achieved IS NOT NULL) AND (marks_total IS NOT NULL)))),
    CONSTRAINT coursework_marks_range_chk CHECK (((marks_achieved IS NULL) OR (marks_total IS NULL) OR (marks_achieved <= marks_total))),
    CONSTRAINT coursework_marks_total_chk CHECK (((marks_total IS NULL) OR (marks_total > (0)::numeric))),
    CONSTRAINT coursework_score_percent_chk CHECK (((score_percent IS NULL) OR ((score_percent >= (0)::numeric) AND (score_percent <= (100)::numeric))))
);

ALTER TABLE public.coursework OWNER TO postgres;

ALTER TABLE public.coursework ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coursework_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.modules (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    credits integer,
    name character varying(255) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.modules OWNER TO postgres;

ALTER TABLE public.modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_preferences (
    user_id bigint NOT NULL,
    home_address character varying(255),
    cityuni_address character varying(255),
    buffer_minutes integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    city_uni_address character varying(255)
);

ALTER TABLE public.user_preferences OWNER TO postgres;

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL
);

ALTER TABLE public.users OWNER TO postgres;

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.auth_codes
    ADD CONSTRAINT auth_codes_pkey PRIMARY KEY (email);

ALTER TABLE ONLY public.coursework
    ADD CONSTRAINT coursework_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT modules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT fk1gwwpqcxuy9xxcrs20vv8oa0m FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.coursework
    ADD CONSTRAINT fke88t9psow849dvt8demokymf7 FOREIGN KEY (module_id) REFERENCES public.modules(id);

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- Completed on 2026-03-23 14:18:19

--
-- PostgreSQL database dump complete
--

\unrestrict f8mx5zOTvs2XqpSZuAuCv5zbmPQjRw2PtNdjmlqIKB9b3uZm6brGdOYDVxEhlyH